services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookings_app_production
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/bookings_app_production
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ./bin/rails server -b 0.0.0.0 -p 3000

volumes:
  db_data:
